// <auto-generated />
using System;
using FlightScoreboard.DateBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightScoreboard.Migrations
{
    [DbContext(typeof(FlightScoreboardContext))]
    [Migration("20230831070331_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightScoreboard.DateBase.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Airline");
                });

            modelBuilder.Entity("FlightScoreboard.DateBase.Airplane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Airplane");
                });

            modelBuilder.Entity("FlightScoreboard.DateBase.AirplaneByAirline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<int>("AirplaneId")
                        .HasColumnType("int");

                    b.Property<int>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("AirplaneId");

                    b.ToTable("AirplaneByAirline");
                });

            modelBuilder.Entity("FlightScoreboard.DateBase.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("FlightScoreboard.DateBase.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<int>("AirplaneByAirlineId")
                        .HasColumnType("int");

                    b.Property<int>("FromCityId")
                        .HasColumnType("int");

                    b.Property<int>("PilotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToCityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("AirplaneByAirlineId");

                    b.HasIndex("FromCityId");

                    b.HasIndex("PilotId");

                    b.HasIndex("ToCityId");

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("FlightScoreboard.DateBase.Pilot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("Pilot");
                });

            modelBuilder.Entity("FlightScoreboard.DateBase.AirplaneByAirline", b =>
                {
                    b.HasOne("FlightScoreboard.DateBase.Airline", "Airline")
                        .WithMany("AirplaneByAirlines")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightScoreboard.DateBase.Airplane", "Airplane")
                        .WithMany("AirplaneByAirlines")
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Airplane");
                });

            modelBuilder.Entity("FlightScoreboard.DateBase.Flight", b =>
                {
                    b.HasOne("FlightScoreboard.DateBase.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightScoreboard.DateBase.AirplaneByAirline", "AirplaneByAirline")
                        .WithMany("Flights")
                        .HasForeignKey("AirplaneByAirlineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlightScoreboard.DateBase.City", "FromCity")
                        .WithMany("FromFlights")
                        .HasForeignKey("FromCityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlightScoreboard.DateBase.Pilot", "Pilot")
                        .WithMany("Flights")
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlightScoreboard.DateBase.City", "ToCity")
                        .WithMany("ToFlights")
                        .HasForeignKey("ToCityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("AirplaneByAirline");

                    b.Navigation("FromCity");

                    b.Navigation("Pilot");

                    b.Navigation("ToCity");
                });

            modelBuilder.Entity("FlightScoreboard.DateBase.Pilot", b =>
                {
                    b.HasOne("FlightScoreboard.DateBase.Airline", "Airline")
                        .WithMany("Pilots")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("FlightScoreboard.DateBase.Airline", b =>
                {
                    b.Navigation("AirplaneByAirlines");

                    b.Navigation("Flights");

                    b.Navigation("Pilots");
                });

            modelBuilder.Entity("FlightScoreboard.DateBase.Airplane", b =>
                {
                    b.Navigation("AirplaneByAirlines");
                });

            modelBuilder.Entity("FlightScoreboard.DateBase.AirplaneByAirline", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("FlightScoreboard.DateBase.City", b =>
                {
                    b.Navigation("FromFlights");

                    b.Navigation("ToFlights");
                });

            modelBuilder.Entity("FlightScoreboard.DateBase.Pilot", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
